# Generated by Django 5.1.6 on 2025-02-26 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='images',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('street_light', 'Street Light'), ('ghanta_gadi', 'Ghanta Gadi'), ('waste_water', 'Waste Water'), ('road', 'Road')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ward_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='complaintimage',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='complaints.complaint'),
        ),
    ]
